name: release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel:
        # linux/386, linux/amd64, linux/arm64
        # windows/386, windows/amd64
        # darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - id: query
        uses: romnn/query-git-action@master

      # - uses: wangyoucao577/go-release-action@v1.32
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     goos: ${{ matrix.goos }}
      #     goarch: ${{ matrix.goarch }}
      #     project_path: "./cmd/devproxy"
      #     binary_name: "devproxy"
      #     extra_files: LICENSE README.md
      #

      - name: Set binary name
        id: bin_name
        env:
          BIN: devproxy-${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          if [ ${{ matrix.goos }} == "windows" ]
          then
            export BIN=$BIN.exe
          fi
          echo "BIN=$BIN" >> $GITHUB_OUTPUT

      - name: Build release binary
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
          LDFLAGS: >
            -w
            -s
            -X main.Version=${{ steps.query.outputs.stable_semver_version }}
            -X main.Rev=${{ steps.query.outputs.stable_build_git_commit }}
        run: >
          go build -a 
          -ldflags="$LDFLAGS"
          -o build/${{ steps.bin_name.outputs.BIN }} 
          github.com/romnn/devproxy/cmd/devproxy

      - name: Upload release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ steps.query.outputs.stable_semver_version }}
          release_name: ${{ steps.query.outputs.stable_semver_version }}
          overwrite: true
          file_glob: true
